version: "3.9"
services:
  kirby:
    build: .
    container_name: kirby
    env_file: .env
    environment:
      MONGO_URI: "mongodb://root:kirby@kirby_db:27017/"
    restart: always

  kirby_db:
    image: mongo:6.0.5
    container_name: kirby_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kirby
    ports:
      - "27017:27017"
    volumes:
      - ~/kirby_db/data:/data/db
